#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

setxkbmap es
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources	# Uncomment to use Xresources colors/settings on startup
xwallpaper --zoom ~/.local/share/bg
xset r rate 300 50 	# Speed xrate up
xcompmgr &		# xcompmgr for transparency
fcitx &
dunst &			# dunst for notifications
unclutter &		# Remove mouse when idlle

