#!/bin/sh

export LF_COLORS="\
~/Documents=01;33:\
~/Downloads=01;33:\
~/.local=01;33:\
~/.config=01;33:\
~/.local/share=01;31:\
~/.config/lf/lfrc=31:\
.git/=01;32:\
.git=32:\
.gitignore=32:\
*.pdf=01;91:\
Makefile=32:\
ln=01;36:\
di=01;34:\
ex=01;35:\
"
